import {StyleSheet} from 'react-native';
import {Colors, Fonts} from 'src/constants';
import {fontScale, scale, setHeight, setWidth} from 'src/utils';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.DEFAULT_WHITE,
  },
  image: {
    top: 0,
    position: 'absolute',
    height: setWidth(100),
    width: setWidth(100),
  },
  mainButtonBack: {
    alignItems: 'flex-start',
  },
  containerButtonBack: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: scale(20),
    width: scale(40),
    height: scale(40),
    borderRadius: 40,
    opacity: 0.8,
    backgroundColor: Colors.DARK_FIVE,
  },
  mainContainer: {
    backgroundColor: Colors.DEFAULT_WHITE,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  titleHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: scale(20),
    marginTop: scale(10),
  },
  titleText: {
    fontSize: fontScale(23),
    lineHeight: fontScale(23) * 1.4,
    fontFamily: Fonts.POPPINS_SEMI_BOLD,
    color: Colors.DEFAULT_BLACK,
  },
  priceText: {
    fontSize: fontScale(23),
    lineHeight: fontScale(23) * 1.4,
    fontFamily: Fonts.POPPINS_SEMI_BOLD,
    color: Colors.DEFAULT_YELLOW,
  },
  subHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: scale(20),
    marginTop: scale(15),
  },
  rowAndCenter: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  ratingText: {
    fontSize: fontScale(13),
    lineHeight: fontScale(13) * 1.4,
    fontFamily: Fonts.POPPINS_BOLD,
    color: Colors.DEFAULT_BLACK,
    marginLeft: scale(5),
  },
  reviewsText: {
    fontSize: fontScale(13),
    lineHeight: fontScale(13) * 1.4,
    fontFamily: Fonts.POPPINS_MEDIUM,
    color: Colors.DEFAULT_BLACK,
    marginLeft: scale(5),
  },
  iconImage: {
    height: scale(20),
    width: scale(20),
  },
  deliveryText: {
    fontSize: fontScale(12),
    lineHeight: fontScale(12) * 1.4,
    fontFamily: Fonts.POPPINS_MEDIUM,
    color: Colors.DEFAULT_BLACK,
    marginLeft: scale(3),
  },
  subMenuContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    paddingHorizontal: scale(20),
    marginTop: scale(20),
    borderColor: Colors.DEFAULT_GREY,
    justifyContent: 'space-evenly',
  },
  subMenuButtonContainer: {
    paddingVertical: scale(15),
    width: setWidth(30),
    alignItems: 'center',
  },
  subMenuButtonText: {
    fontSize: fontScale(13),
    lineHeight: fontScale(13) * 1.4,
    fontFamily: Fonts.POPPINS_SEMI_BOLD,
    color: Colors.DEFAULT_BLACK,
  },
  detailsContainer: {
    paddingHorizontal: scale(20),
  },
  detailHeader: {
    fontSize: fontScale(15),
    lineHeight: fontScale(15) * 1.4,
    fontFamily: Fonts.POPPINS_SEMI_BOLD,
    color: Colors.DEFAULT_BLACK,
    marginTop: scale(10),
    marginBottom: scale(2),
  },
  detailContent: {
    fontSize: fontScale(12),
    lineHeight: fontScale(12) * 1.4,
    fontFamily: Fonts.POPPINS_SEMI_BOLD,
    color: Colors.INACTIVE_GREY,
    textAlign: 'justify',
  },
  buttonsContainer: {
    bottom: 0,
    position: 'absolute',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: Colors.DEFAULT_WHITE,
    width: setWidth(100),
    paddingHorizontal: setWidth(5),
    paddingVertical: setWidth(2.5),
  },
  itemAddContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: Colors.LIGHT_GREY2,
    height: setHeight(6),
    width: setWidth(30),
    justifyContent: 'center',
    borderRadius: 8,
  },
  itemCountText: {
    color: Colors.DEFAULT_BLACK,
    fontSize: 14,
    lineHeight: 14 * 1.4,
    fontFamily: Fonts.POPPINS_SEMI_BOLD,
    marginHorizontal: 8,
  },
  cartButton: {
    backgroundColor: Colors.DEFAULT_GREEN,
    height: setHeight(6),
    width: setWidth(58),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 8,
  },
  cartButtonText: {
    color: Colors.DEFAULT_WHITE,
    fontSize: 14,
    lineHeight: 14 * 1.4,
    fontFamily: Fonts.POPPINS_MEDIUM,
  },
});
